Repository MotuS-Web/MotuS-Backend, pull requests merged in 2023-10, with the labels that each got.

#34 [BE / feat] Create VideoDetailResponseDTO
  src/main/java/com/hallym/rehab/domain/video/controller/VideoController.java
  src/main/java/com/hallym/rehab/domain/video/dto/VideoDetailResponseDTO.java
  src/main/java/com/hallym/rehab/domain/video/entity/Video.java
  src/main/java/com/hallym/rehab/domain/video/service/VideoService.java
  src/main/java/com/hallym/rehab/domain/video/service/VideoServiceImpl.java
Labels: 🔨 feature

#38 [BE / refactor] 서버 port 번호를 8081으로 변경한다.
  src/main/resources/application.tar.gpg
Labels: 🖥️ backend, ⚙️ infra, 🏢 release

#40 [Devops / infra, release] DockerFile을 만들어 Image를 빌드하고, Hub에 Push하여 동일한 컨테이너 환경을 제공한다
   .dockerignore
  Dockerfile
Labels: ⚙️ infra, 🏢 release

#41 [BE, refactor]
  Dockerfile
  src/main/resources/application.tar.gpg
Labels: 📦 DB, ⚙️ infra, 🔧 fix_issue, 🏢 release

#43 [BE / Bug, refator] DockerFile에 신규 스크립트를 추가하고, docs 파일을 정리한다.
   .dockerignore
  .github/ISSUE_TEMPLATE/🐛-bug.md
  Dockerfile
  README.md
  appspec.yml
  docs/ObjectStorageGuide_EN.md
  docs/ObjectStorageGuide_KO.md
  src/main/java/website/motus/domain/video/dto/pagedto/VideoPageRequestDTO.java
  src/main/java/website/motus/domain/video/service/VideoService.java
  src/main/java/website/motus/domain/video/service/VideoServiceImpl.java
  src/main/resources/application.tar.gpg
Labels: ⚙️ infra, 🛠️ refactoring, 🐛 bug_report

#44 [Docs] LISENSE와 CONTRIBUTE를 포함한 개발문서를 작성합니다.
  LICENSE_3rd.md
  README.md
  docs/CONTRIBUTING.md
Labels: 📰 documentation

#45 [BE] Change workflow file and PR & Issue Template comments
  .github/ISSUE_TEMPLATE/✅-feature.md
  .github/ISSUE_TEMPLATE/🐛-bug.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/deploy.yml
Labels: 📰 documentation
