Repository MotuS-Web/MotuS-Backend, pull requests merged in 2023-08, with the labels that each got.

#2 [BE] 백엔드 프로젝트 디렉토리 구조를 설계하고 개발 환경을 세팅한다.
  .github/ISSUE_TEMPLATE/✅-feature.md
  .github/ISSUE_TEMPLATE/🐛-bug.md
  .github/PULL_REQUEST_TEMPLATE.md
  .gitignore
  build.gradle
  gradlew
  src/main/java/com/hallym/rehab/RehabApplication.java
  src/main/java/com/hallym/rehab/domain/program/entity/Category.java
  src/main/java/com/hallym/rehab/domain/program/entity/Program.java
  src/main/java/com/hallym/rehab/domain/program/entity/ProgramVideo.java
  src/main/java/com/hallym/rehab/domain/program/repository/ProgramRepository.java
  src/main/java/com/hallym/rehab/domain/program/repository/ProgramVideoRepository.java
  src/main/java/com/hallym/rehab/domain/user/entity/Member.java
  src/main/java/com/hallym/rehab/domain/user/entity/MemberRole.java
  src/main/java/com/hallym/rehab/domain/user/repository/MemberRepository.java
  src/main/java/com/hallym/rehab/global/baseEntity/BaseTimeEntity.java
  src/main/resources/application.properties
  src/main/resources/log4j2.yml
  src/test/java/com/hallym/rehab/RehabApplicationTests.java
  src/test/java/com/hallym/rehab/repository/MemberRepositoryTests.java
  src/test/java/com/hallym/rehab/repository/ProgramReposotoryTests.java
Labels: 🖥️ backend, ⚙️ infra

#5 [Bugfix/BE] Bean Overriding이 되어 gradlew Build가 되지 않는 현상 수정
  src/test/java/com/hallym/rehab/RehabApplicationTests.java
  src/test/java/com/hallym/rehab/domain/member/MemberRepositoryTests.java
  src/test/java/com/hallym/rehab/domain/program/ProgramReposotoryTests.java
Labels: 🖥️ backend, 🐛 bug_report

#9 [BE] Object Storage에 대한 엑세스 및 삽입, 삭제 기능 구현 및 테스트
  .gitignore
  build.gradle
  src/main/java/com/hallym/rehab/global/config/S3Client.java
  src/main/resources/application.yml
  src/test/java/com/hallym/rehab/global/config/S3ClientTest.java
Labels: 🖥️ backend, 📈 test

#10 [BE] S3 업로드 서비스로직 구현
  src/main/java/com/hallym/rehab/domain/program/controller/ProgramController.java
  src/main/java/com/hallym/rehab/domain/program/dto/ProgramRequestDTO.java
  src/main/java/com/hallym/rehab/domain/program/entity/ProgramVideo.java
  src/main/java/com/hallym/rehab/domain/program/service/ProgramService.java
  src/main/java/com/hallym/rehab/domain/program/service/ProgramServiceImpl.java
  src/test/java/com/hallym/rehab/domain/program/ProgramReposotoryTests.java
  src/test/java/com/hallym/rehab/global/config/S3ClientTest.java
Labels: 📦 DB, 🖥️ backend, 🔨 feature

#11 [BE] 사용자 로그인 시 JWT 이용한 토큰 인증 방식 구현 및 Program default service 로직 구현
  build.gradle
  src/main/java/com/hallym/rehab/TestController.java
  src/main/java/com/hallym/rehab/domain/program/dto/ProgramDTO.java
  src/main/java/com/hallym/rehab/domain/program/dto/ProgramVideoDTO.java
  src/main/java/com/hallym/rehab/domain/program/entity/Category.java
  src/main/java/com/hallym/rehab/domain/program/entity/Position.java
  src/main/java/com/hallym/rehab/domain/program/entity/Program.java
  src/main/java/com/hallym/rehab/domain/program/entity/ProgramVideo.java
  src/main/java/com/hallym/rehab/domain/program/service/ProgramService.java
  src/main/java/com/hallym/rehab/domain/program/service/ProgramServiceImpl.java
  src/main/java/com/hallym/rehab/domain/user/controller/UserController.java
  src/main/java/com/hallym/rehab/domain/user/dto/MemberJoinDTO.java
  src/main/java/com/hallym/rehab/domain/user/dto/PasswordChangeDTO.java
  src/main/java/com/hallym/rehab/domain/user/entity/Member.java
  src/main/java/com/hallym/rehab/domain/user/repository/MemberRepository.java
  src/main/java/com/hallym/rehab/domain/user/service/APIUserService.java
  src/main/java/com/hallym/rehab/domain/user/service/APIUserServiceImpl.java
  src/main/java/com/hallym/rehab/global/config/AppConfig.java
  src/main/java/com/hallym/rehab/global/config/CustomSecurityConfig.java
  src/main/java/com/hallym/rehab/global/exception/IncorrectNameException.java
  src/main/java/com/hallym/rehab/global/exception/IncorrectPasswordException.java
  src/main/java/com/hallym/rehab/global/pageDTO/PageRequestDTO.java
  src/main/java/com/hallym/rehab/global/pageDTO/PageResponseDTO.java
  src/main/java/com/hallym/rehab/global/security/APIUserDetailsService.java
  src/main/java/com/hallym/rehab/global/security/Encrypt.java
  src/main/java/com/hallym/rehab/global/security/dto/APIUserDTO.java
  src/main/java/com/hallym/rehab/global/security/exception/AccessTokenException.java
  src/main/java/com/hallym/rehab/global/security/exception/RefreshTokenException.java
  src/main/java/com/hallym/rehab/global/security/filter/APILoginFilter.java
  src/main/java/com/hallym/rehab/global/security/filter/RefreshTokenFilter.java
  src/main/java/com/hallym/rehab/global/security/filter/TokenCheckFilter.java
  src/main/java/com/hallym/rehab/global/security/handler/APILoginSuccessHandler.java
  src/main/java/com/hallym/rehab/global/security/util/JWTUtil.java
  src/test/java/com/hallym/rehab/RehabApplicationTests.java
  src/test/java/com/hallym/rehab/domain/program/ProgramReposotoryTests.java
Labels: 🖥️ backend, 🔨 feature, 🔑 auth

#12 [BE] Program 서비스 로직 변경 및 기타 수정사항 반영
  src/main/java/com/hallym/rehab/domain/program/controller/ProgramController.java
  src/main/java/com/hallym/rehab/domain/program/dto/ProgramRequestDTO.java
  src/main/java/com/hallym/rehab/domain/program/entity/Program.java
  src/main/java/com/hallym/rehab/domain/program/entity/ProgramVideo.java
  src/main/java/com/hallym/rehab/domain/program/repository/ProgramVideoRepository.java
  src/main/java/com/hallym/rehab/domain/program/service/ProgramService.java
  src/main/java/com/hallym/rehab/domain/program/service/ProgramServiceImpl.java
  src/main/resources/application.yml
Labels: 🖥️ backend, 🔨 feature, 🔧 fix_issue, 🛠️ refactoring

#14 [BE] Video 관련 로직 대규모 변경 및 매핑 테이블 추가, 코드 유지보수
  src/main/java/com/hallym/rehab/domain/program/controller/ProgramAdminController.java
  src/main/java/com/hallym/rehab/domain/program/controller/ProgramController.java
  src/main/java/com/hallym/rehab/domain/program/controller/ProgramUserController.java
  src/main/java/com/hallym/rehab/domain/program/controller/VideoAdminController.java
  src/main/java/com/hallym/rehab/domain/program/controller/VideoUserController.java
  src/main/java/com/hallym/rehab/domain/program/dto/ProgramVideoDTO.java
  src/main/java/com/hallym/rehab/domain/program/dto/act/ActResponseDTO.java
  src/main/java/com/hallym/rehab/domain/program/dto/program/ProgramDetailResponseDTO.java
  src/main/java/com/hallym/rehab/domain/program/dto/program/ProgramMainResponseDTO.java
  src/main/java/com/hallym/rehab/domain/program/dto/program/ProgramRequestDTO.java
  src/main/java/com/hallym/rehab/domain/program/dto/upload/UploadFileDTO.java
  src/main/java/com/hallym/rehab/domain/program/dto/video/SwapOrdRequestDTO.java
  src/main/java/com/hallym/rehab/domain/program/dto/video/VideoRequestDTO.java
  src/main/java/com/hallym/rehab/domain/program/dto/video/VideoResponseDTO.java
  src/main/java/com/hallym/rehab/domain/program/entity/Program.java
  src/main/java/com/hallym/rehab/domain/program/entity/ProgramVideo.java
  src/main/java/com/hallym/rehab/domain/program/entity/ProgramVideo_Member.java
  src/main/java/com/hallym/rehab/domain/program/entity/Program_Member.java
  src/main/java/com/hallym/rehab/domain/program/repository/ProgramVideoRepository.java
  src/main/java/com/hallym/rehab/domain/program/service/ProgramService.java
  src/main/java/com/hallym/rehab/domain/program/service/ProgramServiceImpl.java
  src/main/java/com/hallym/rehab/domain/program/service/VideoService.java
  src/main/java/com/hallym/rehab/domain/program/service/VideoServiceImpl.java
  src/main/java/com/hallym/rehab/domain/user/entity/Member.java
Labels: 📦 DB, 🖥️ backend, 🔨 feature, 🛠️ refactoring

#15 [BE] Video와 Member간에 Matrix 테이블 생성 및 서비스 로직 구현
  src/main/java/com/hallym/rehab/domain/program/controller/ProgramUserController.java
  src/main/java/com/hallym/rehab/domain/program/controller/VideoUserController.java
  src/main/java/com/hallym/rehab/domain/program/dto/video/MatrixRequestDTO.java
  src/main/java/com/hallym/rehab/domain/program/entity/Program.java
  src/main/java/com/hallym/rehab/domain/program/entity/Program_Member.java
  src/main/java/com/hallym/rehab/domain/program/entity/Video.java
  src/main/java/com/hallym/rehab/domain/program/entity/Video_Member.java
  src/main/java/com/hallym/rehab/domain/program/repository/ProgramVideoRepository.java
  src/main/java/com/hallym/rehab/domain/program/repository/Program_MemberRepository.java
  src/main/java/com/hallym/rehab/domain/program/repository/VideoRepository.java
  src/main/java/com/hallym/rehab/domain/program/repository/Video_MemberRepository.java
  src/main/java/com/hallym/rehab/domain/program/service/ProgramService.java
  src/main/java/com/hallym/rehab/domain/program/service/ProgramServiceImpl.java
  src/main/java/com/hallym/rehab/domain/program/service/VideoService.java
  src/main/java/com/hallym/rehab/domain/program/service/VideoServiceImpl.java
  src/main/java/com/hallym/rehab/domain/user/entity/Member.java
  src/test/java/com/hallym/rehab/domain/program/ProgramReposotoryTests.java
Labels: 🖥️ backend, 🔨 feature

#16 [BE] Video Entity에 frame column 추가
  src/main/java/com/hallym/rehab/domain/program/dto/video/VideoRequestDTO.java
  src/main/java/com/hallym/rehab/domain/program/entity/Video.java
  src/main/java/com/hallym/rehab/domain/program/service/VideoServiceImpl.java
Labels: 🖥️ backend, 🔨 feature

#17 [BE] 비디오 조회기능 추가
  src/main/java/com/hallym/rehab/domain/program/controller/ProgramUserController.java
  src/main/java/com/hallym/rehab/domain/program/controller/VideoUserController.java
  src/main/java/com/hallym/rehab/domain/program/dto/video/VideoResponseDTO.java
  src/main/java/com/hallym/rehab/domain/program/repository/VideoRepository.java
  src/main/java/com/hallym/rehab/domain/program/service/VideoService.java
  src/main/java/com/hallym/rehab/domain/program/service/VideoServiceImpl.java
Labels: 🖥️ backend, 🔨 feature, 🛠️ refactoring

#18 [refactor/BE] 클래스의 어노테이션 수정 및 프로그램 등록 시 리턴타입
  .github/workflows/gradle.yml
  src/main/java/com/hallym/rehab/domain/program/controller/ProgramAdminController.java
  src/main/java/com/hallym/rehab/domain/program/dto/act/ActResponseDTO.java
  src/main/java/com/hallym/rehab/domain/program/dto/video/MatrixRequestDTO.java
  src/main/java/com/hallym/rehab/domain/program/entity/Program.java
  src/main/java/com/hallym/rehab/domain/program/entity/Video.java
  src/main/java/com/hallym/rehab/domain/program/entity/Video_Member.java
  src/main/java/com/hallym/rehab/domain/program/service/ProgramService.java
  src/main/java/com/hallym/rehab/domain/program/service/ProgramServiceImpl.java
  src/main/java/com/hallym/rehab/domain/program/service/VideoServiceImpl.java
  src/main/java/com/hallym/rehab/domain/user/entity/Member.java
  src/main/resources/sampleVideo.mp4
  src/test/java/com/hallym/rehab/domain/program/ProgramReposotoryTests.java
Labels: 🖥️ backend, 🔧 fix_issue, 🛠️ refactoring

#19 [refactor/BE] 비디오 순번 변경 알고리즘 변경
  src/main/java/com/hallym/rehab/domain/program/controller/VideoAdminController.java
  src/main/java/com/hallym/rehab/domain/program/controller/VideoUserController.java
  src/main/java/com/hallym/rehab/domain/program/dto/video/ChangeOrdRequestDTO.java
  src/main/java/com/hallym/rehab/domain/program/dto/video/SwapOrdRequestDTO.java
  src/main/java/com/hallym/rehab/domain/program/service/VideoService.java
  src/main/java/com/hallym/rehab/domain/program/service/VideoServiceImpl.java
Labels: 🖥️ backend, 🛠️ refactoring

#21 [feat/BE] QueryDsl 동적 쿼리를 이용한 도메인 페이징 처리
  build.gradle
  src/main/java/com/hallym/rehab/domain/program/controller/ProgramUserController.java
  src/main/java/com/hallym/rehab/domain/program/controller/VideoUserController.java
  src/main/java/com/hallym/rehab/domain/program/dto/act/ActResponseDTO.java
  src/main/java/com/hallym/rehab/domain/program/dto/program/ProgramHistoryDTO.java
  src/main/java/com/hallym/rehab/domain/program/dto/program/ProgramListResponseDTO.java
  src/main/java/com/hallym/rehab/domain/program/dto/video/MetricsRequestDTO.java
  src/main/java/com/hallym/rehab/domain/program/entity/Program.java
  src/main/java/com/hallym/rehab/domain/program/entity/ProgramHistory.java
  src/main/java/com/hallym/rehab/domain/program/entity/Video_Member.java
  src/main/java/com/hallym/rehab/domain/program/repository/ProgramHistoryRepository.java
  src/main/java/com/hallym/rehab/domain/program/repository/ProgramRepository.java
  src/main/java/com/hallym/rehab/domain/program/repository/Program_MemberRepository.java
  src/main/java/com/hallym/rehab/domain/program/repository/VideoRepository.java
  src/main/java/com/hallym/rehab/domain/program/repository/Video_MemberRepository.java
  src/main/java/com/hallym/rehab/domain/program/repository/search/ProgramSearch.java
  src/main/java/com/hallym/rehab/domain/program/repository/search/ProgramSearchImpl.java
  src/main/java/com/hallym/rehab/domain/program/service/ProgramService.java
  src/main/java/com/hallym/rehab/domain/program/service/ProgramServiceImpl.java
  src/main/java/com/hallym/rehab/domain/program/service/VideoService.java
  src/main/java/com/hallym/rehab/domain/program/service/VideoServiceImpl.java
  src/test/java/com/hallym/rehab/domain/program/ProgramRepositoryTests.java
Labels: 🖥️ backend, 🔨 feature, 🔧 fix_issue, 📈 test

#22 [refactor/BE] video의 playTime col 추가
  src/main/java/com/hallym/rehab/domain/program/dto/act/ActResponseDTO.java
  src/main/java/com/hallym/rehab/domain/program/dto/program/ProgramListResponseDTO.java
  src/main/java/com/hallym/rehab/domain/program/dto/video/VideoRequestDTO.java
  src/main/java/com/hallym/rehab/domain/program/entity/Video.java
  src/main/java/com/hallym/rehab/domain/program/repository/search/ProgramSearchImpl.java
  src/main/java/com/hallym/rehab/domain/program/service/ProgramServiceImpl.java
  src/main/java/com/hallym/rehab/domain/program/service/VideoServiceImpl.java
Labels: 🖥️ backend, 🔨 feature
