Repository MotuS-Web/MotuS-Backend, pull requests merged in 2023-09, with the labels that each got.

#23 [test/BE] 비디오 등록, 삭제, 조회 기능 테스트
  src/main/java/com/hallym/rehab/domain/program/dto/video/VideoRequestDTO.java
  src/main/java/com/hallym/rehab/domain/program/entity/Program.java
  src/main/java/com/hallym/rehab/domain/program/service/VideoServiceImpl.java
  src/main/resources/sample.json
  src/main/resources/sample.mp4
  src/test/java/com/hallym/rehab/domain/program/service/VideoServiceImplTest.java
  src/test/java/com/hallym/rehab/global/config/S3ClientTest.java
Labels: 🖥️ backend, 🛠️ refactoring, 📈 test

#25 [refactor/BE] @PreAuthorize 어노테이션을 이용하여, 로그인한 사용자의 권한에 따라 엔드포인트 접근을 허용한다
  src/main/java/com/hallym/rehab/domain/program/controller/ProgramAdminController.java
  src/main/java/com/hallym/rehab/domain/program/controller/ProgramUserController.java
  src/main/java/com/hallym/rehab/domain/program/controller/VideoAdminController.java
  src/main/java/com/hallym/rehab/domain/program/controller/VideoUserController.java
  src/main/java/com/hallym/rehab/domain/program/dto/program/ProgramRequestDTO.java
  src/main/java/com/hallym/rehab/domain/program/entity/Program.java
  src/main/java/com/hallym/rehab/domain/program/entity/Video.java
  src/main/java/com/hallym/rehab/domain/program/service/ProgramService.java
  src/main/java/com/hallym/rehab/domain/program/service/ProgramServiceImpl.java
  src/main/java/com/hallym/rehab/domain/user/controller/UserController.java
Labels: 🖥️ backend, 🔑 auth, 🛠️ refactoring

#26 [BE] refactor, feat, bug 등등 개발사항 반영
  src/main/java/com/hallym/rehab/domain/program/controller/ProgramUserController.java
  src/main/java/com/hallym/rehab/domain/program/controller/VideoUserController.java
  src/main/java/com/hallym/rehab/domain/program/dto/video/VideoRequestDTO.java
  src/main/java/com/hallym/rehab/domain/program/dto/video/VideoResponseDTO.java
  src/main/java/com/hallym/rehab/domain/program/dto/video/VideoUrl.java
  src/main/java/com/hallym/rehab/domain/program/entity/Video.java
  src/main/java/com/hallym/rehab/domain/program/service/VideoService.java
Labels: 🖥️ backend, 🔨 feature, 🔧 fix_issue, 🛠️ refactoring

#27 [fix/BE] Video 목록 조회 테스트 시, 메소드 명 오류를 해결한다.
  .github/workflows/gradle.yml
  src/test/java/com/hallym/rehab/domain/program/service/VideoServiceImplTest.java
Labels: 🖥️ backend, 🔧 fix_issue
